#!/bin/bash
export k8s_pod=$1
for line in $(kubectl get pods --all-namespaces | \
  grep $k8s_pod | awk '{print $2}'); do
    echo "kubectl exec -ti $line -n msdataworkshop sh"
    kubectl exec -ti $line -n msdataworkshop sh
done
